# Generated by Django 5.2.3 on 2025-06-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_categoria_alter_contapagar_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='grupo_parcelamento',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_parcela',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='total_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
