# Generated by Django 5.2.3 on 2025-07-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_contapagar_status_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='info_pagamento',
            field=models.TextField(blank=True, null=True, verbose_name='Informações do Pagamento'),
        ),
    ]
